name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Ensure Gradle wrapper exists
      run: |
        if [ ! -f ./gradlew ]; then
          echo "Gradle wrapper not found. Downloading..."
          curl -sLo gradlew https://services.gradle.org/distributions/gradle-8.2-bin.zip
          unzip -q gradle-8.2-bin.zip
          mv gradle-8.2/bin/gradlew .
          chmod +x gradlew
        fi

    - name: Make Gradle wrapper executable
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/libs/*.jar

    - name: Run unit tests
      run: ./gradlew test

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: build/reports/tests/test/*

    - name: Run Deployment
      run: java -jar build/libs/PlayWordle.jar